apiRules:
- include:
    uidRegex: ^Hskim.Model
    type: Namespace
- include:
    uidRegex: ^Hskim.View
    type: Namespace
- include:
    uidRegex: ^Hskim.Mediator
    type: Namespace
- include:
    uidRegex: ^Hskim
    type: Namespace
- exclude:
    uidRegex: .*
    type: Namespace