name: Build and Deploy

'on':
  push:
    branches:
      - main
      - rc
  workflow_dispatch: null
jobs:
  buildDocs:
    name: Build Docs
    runs-on: windows-latest
    if: "!contains(github.event.head_commit.message, 'github-actions')"
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Docfx
        run: choco install -y docfx
      - name: Use README.md as index.md
        run: cp README.md Documentation/index.md
      - name: Build Docfx
        run: docfx Documentation/docfx.json
      - name: Upload site artifact
        uses: actions/upload-artifact@v4  
        with:
          name: _site
          path: _site
  deployDocs:
    name: Deploy Docs
    needs:
      - buildDocs
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'github-actions')"
    steps:
      - name: Checkout hskim881028/ci-test Repository
        uses: actions/checkout@v2
        with:
          repository: hskim881028/ci-test
          token: '${{ secrets.PAT }}'
      - name: Download site artifact
        uses: actions/download-artifact@v4
        with:
          name: _site
          path: _site
      - name: Deploy to hskim881028/ci-test Repository
        run: |
          mkdir -p docs
          cp -r _site/* docs/
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add docs
          git commit -m "Deploy docs by github-actions"
          git push
  buildForAllSupportedPlatforms:
    name: 'Build for ${{ matrix.targetPlatform }}'
    needs:
      - deployDocs
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'github-actions')"
    strategy:
      matrix:
        targetPlatform:
          - StandaloneOSX
          - StandaloneWindows64
    steps:
      - name: Free Disk Space
        uses: jlumbroso/free-disk-space@main
        with:
          tool-cache: false
          android: true
          dotnet: false
          haskell: false
          large-packages: false
          docker-images: false
          swap-storage: false
      - name: Check out
        uses: actions/checkout@v4
      - name: Cache library
        uses: actions/cache@v4
        with:
          path: Library
          key: >-
            Library-${{ hashFiles('Assets/**', 'Packages/**',
            'ProjectSettings/**') }}
          restore-keys: |
            Library-
      - name: Unity build
        uses: game-ci/unity-builder@v4
        env:
          UNITY_LICENSE: '${{ secrets.UNITY_LICENSE }}'
          UNITY_EMAIL: '${{ secrets.UNITY_EMAIL }}'
          UNITY_PASSWORD: '${{ secrets.UNITY_PASSWORD }}'
        with:
          targetPlatform: '${{ matrix.targetPlatform }}'
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: 'Build-${{ matrix.targetPlatform }}'
          path: 'build/${{ matrix.targetPlatform }}'
  notifySlack:
    name: Notify Slack
    needs:
      - buildForAllSupportedPlatforms
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'github-actions')"
    steps:
      - name: Notify to Slack
        uses: 8398a7/action-slack@v3
        with:
          status: custom
          custom_payload: |
            {
              "text": "<https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}|Artifact>"
            }
        env:
          SLACK_WEBHOOK_URL: '${{ secrets.SLACK_WEBHOOK_URL }}'
