name: Build

on:
  push:
    branches:
      - main
      - rc
  workflow_dispatch:

permissions:
  actions: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false
  
jobs:
  buildDocs:
    name: Build and Deploy Docs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Dotnet Setup
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.x
      - run: dotnet tool update -g docfx

      - name: Build Docfx
        run: docfx Documentation/docfx.json

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          name: _site
          path: _site
          
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

  buildForAllSupportedPlatforms:
    name: Build for ${{ matrix.targetPlatform }}
    runs-on: ubuntu-latest    
    needs: [buildDocs]
    strategy:
      matrix:
        targetPlatform:
          - StandaloneOSX
          - StandaloneWindows64

    steps:
     # Cleanup disk space
      - name: Free Disk Space
        uses: jlumbroso/free-disk-space@main
        with:
          tool-cache: false
          android: true
          dotnet: false
          haskell: false
          large-packages: false
          docker-images: false
          swap-storage: false
          
      # Check Out
      - name: Check out
        uses: actions/checkout@v4

      # Cache Library
      - name: Cache library
        uses: actions/cache@v4
        with:
          path: Library
          key: Library-${{ hashFiles('Assets/**', 'Packages/**', 'ProjectSettings/**') }}
          restore-keys: |
            Library-
  
      # Unity Build
      - name: Unity build
        uses: game-ci/unity-builder@v4
        env:          
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}          
        with:
          targetPlatform: ${{ matrix.targetPlatform }}

      # Upload Artifact
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: Build-${{ matrix.targetPlatform }}
          path: build/${{ matrix.targetPlatform }}

  notifySlack:
    name: Notify Slack
    needs: [buildForAllSupportedPlatforms]
    runs-on: ubuntu-latest    
    steps:
      - name: Notify to Slack
        uses: 8398a7/action-slack@v3
        with:
          status: custom
          custom_payload: |
            {
              "text": "<https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}|Artifact>"
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
